id = "grianlang3zed"
name = "GrianLang3Zed"
version = "0.0.1"
schema_version = 1
authors = ["Grian <grianguy32@gmail.com>"]
description = "A zed extension that provides support for grianlang3"
repository = "https://github.com/grian32/grianlang3zed"

[grammars.grianlang3]
repository = "https://github.com/grian32/tree-sitter-grianlang3"
rev = "a464f01cb5ac71141a22005cc899f2fd4dc897b0"
